### ISSUE TITLE
Panel crashes when applying this icon in xfce4 environment.

### ISSUE THREAD

**Issue by Hayao0819** [yeyushengfan258/McMuse-circle#2]
In the Xfce4 environment of ArchLinux, when install.sh is executed in user mode, and after installation, the icon crashes and the panel crashes and cannot be restarted.
 If I change to another icon, the panel will start normally.

**Comment by yeyushengfan258** [comment]
The desktop is not supported yet, sorry.

**Comment by Hayao0819** [comment]
understood!
